name: custom workflow 
on: [push,workflow_dispatch]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: hello world step
        run: echo "hello world!"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello world!"  
      - name: checkout code 
        uses: actions/checkout@v3
      - name: restore dependencies
        #run: echo "restoring dependencies..."
        run: dotnet restore
      - name: build app
        #run: echo "building app..."
        run: dotnet build --no-restore
  say_bye:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: say bye
        run: echo "bye"
  successJob:
    needs: build
    if: Success()
    runs-on: ubuntu-latest
    steps:
      - name: say success
        run: echo "success"

  failed_job:
    needs: build
    if: Failure()
    runs-on: ubuntu-latest
    steps:
      - name: say failed
        run: echo "failed"