name: Test Project

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: start working
        run: echo "hello iam working now."
      - name: Get code
        uses: actions/checkout@v6
      - name: download dot net
        run: dotnet restore
      - name: restore dependencies
        run: echo "hello iam working now."
