name: Test Project

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: start working
        run: echo "hello iam working now."
      - name: Get code
        uses: actions/checkout@v6
      - name: setup dot net
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: download dot net
        run: dotnet restore
      - name: restore dependencies
        run: echo "hello iam working now."
      - name: build app
        run: dotnet build --no-restore
      - name: test app
        run: echo "finsh good building."
